// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetFiltered(arg1:number,arg2:number,arg3:any,arg4:any,arg5:any,arg6:any,arg7:any,arg8:any):Promise<Array<api.ParialAnime>>;

export function GetFullInfo(arg1:number):Promise<api.FullAnime>;

export function GetTrendingList(arg1:number,arg2:number):Promise<Array<api.ParialAnime>>;

export function SafeQuit(arg1:number,arg2:number):Promise<void>;
