// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFullInfo(arg1) {
  return window['go']['main']['App']['GetFullInfo'](arg1);
}

export function GetNewestList(arg1, arg2) {
  return window['go']['main']['App']['GetNewestList'](arg1, arg2);
}
