// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetNewestList(arg1:number,arg2:number):Promise<Array<api.Anime>>;

export function Greet(arg1:string):Promise<string>;
