// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetFullInfo(arg1:number):Promise<api.FullAnime>;

export function GetNewestList(arg1:number,arg2:number):Promise<Array<api.ParialAnime>>;

export function SafeQuit(arg1:number,arg2:number):Promise<void>;
