// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFiltered(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['GetFiltered'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetFullInfo(arg1) {
  return window['go']['main']['App']['GetFullInfo'](arg1);
}

export function GetTrendingList(arg1, arg2) {
  return window['go']['main']['App']['GetTrendingList'](arg1, arg2);
}

export function SafeQuit(arg1, arg2) {
  return window['go']['main']['App']['SafeQuit'](arg1, arg2);
}
